name: zeuxcg.org
url: http://zeuxcg.org
disqusid: http://zeuxcg.org
markdown: redcarpet
redcarpet:
  extensions: ['no_intra_emphasis', 'autolink', 'superscript', 'footnotes', 'tables']
permalink: /:year/:month/:day/:title/
gems:
  - jekyll-redirect-from