name: zeuxcg.org
url: http://zeuxcg.org/
markdown: redcarpet
redcarpet:
  extensions: ['no_intra_emphasis', 'autolink', 'superscript', 'footnotes']
permalink: /:year/:month/:day/:title/
gems:
  - jekyll-redirect-from